# Config file for automatic testing at travis-ci.org
jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.5
        - 3.6

      # Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
      install:
        - pip install --progress-bar off -U tox-travis
        - pip install --progress-bar off -r requirements.txt
        - pip install --progress-bar off -r travis-requirements.txt

      # Command to run tests, e.g. python setup.py test
      script:
        - tox


stages:
  - test
